#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-out.XXXXXX)

cat > $payload <&0

export DOCKER_HOST="$(jq -r '.source.host // ""' < $payload)"
load_certs "$payload"

name="$(jq -r '.params.name // false' < $payload)"
image="$(jq -r '.params.image // ""' < $payload)"
repository="$(cat "${image}/repository")"
digest="$(cat "${image}/digest")"

image_name="${repository}@${digest}"

# if docker service inspect "${name}"; then

# fi

service_id="$(docker service create --name "${name}" "$image_name")"

jq -n "{
  version: {
    id: $(echo "$service_id" | jq -R .)
  },
  metadata: [
    { name: \"image\", value: $(echo $image_name | jq -R .) }
  ]
}" >&3
