#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

export DOCKER_HOST="$(jq -r '.source.host // ""' < $payload)"
load_certs "$payload"

name="$(jq -r '.params.name // false' < $payload)"
image="$(jq -r '.params.image // ""' < $payload)"
repository="$(cat "${image}/repository")"
digest="$(cat "${image}/digest")"

image_name="${repository}@${digest}"

# if docker service inspect "${name}"; then

# fi

jq -n "{}" >&3
